// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package migration_test

import (
	"context"
	"sync"

	"github.com/FuturFusion/migration-manager/internal/migration"
)

// Ensure, that WindowServiceMock does implement migration.WindowService.
// If this is not the case, regenerate this file with moq.
var _ migration.WindowService = &WindowServiceMock{}

// WindowServiceMock is a mock implementation of migration.WindowService.
//
//	func TestSomethingThatUsesWindowService(t *testing.T) {
//
//		// make and configure a mocked migration.WindowService
//		mockedWindowService := &WindowServiceMock{
//			CreateFunc: func(ctx context.Context, window migration.Window) (migration.Window, error) {
//				panic("mock out the Create method")
//			},
//			DeleteByNameAndBatchFunc: func(ctx context.Context, queueSvc migration.QueueService, name string, batchName string) error {
//				panic("mock out the DeleteByNameAndBatch method")
//			},
//			GetAllFunc: func(ctx context.Context) (migration.Windows, error) {
//				panic("mock out the GetAll method")
//			},
//			GetAllByBatchFunc: func(ctx context.Context, batchName string) (migration.Windows, error) {
//				panic("mock out the GetAllByBatch method")
//			},
//			GetByNameAndBatchFunc: func(ctx context.Context, name string, batchName string) (*migration.Window, error) {
//				panic("mock out the GetByNameAndBatch method")
//			},
//			ReplaceByBatchFunc: func(ctx context.Context, queueSvc migration.QueueService, batchName string, windows migration.Windows) error {
//				panic("mock out the ReplaceByBatch method")
//			},
//			UpdateFunc: func(ctx context.Context, window *migration.Window) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedWindowService in code that requires migration.WindowService
//		// and then make assertions.
//
//	}
type WindowServiceMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, window migration.Window) (migration.Window, error)

	// DeleteByNameAndBatchFunc mocks the DeleteByNameAndBatch method.
	DeleteByNameAndBatchFunc func(ctx context.Context, queueSvc migration.QueueService, name string, batchName string) error

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func(ctx context.Context) (migration.Windows, error)

	// GetAllByBatchFunc mocks the GetAllByBatch method.
	GetAllByBatchFunc func(ctx context.Context, batchName string) (migration.Windows, error)

	// GetByNameAndBatchFunc mocks the GetByNameAndBatch method.
	GetByNameAndBatchFunc func(ctx context.Context, name string, batchName string) (*migration.Window, error)

	// ReplaceByBatchFunc mocks the ReplaceByBatch method.
	ReplaceByBatchFunc func(ctx context.Context, queueSvc migration.QueueService, batchName string, windows migration.Windows) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, window *migration.Window) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Window is the window argument value.
			Window migration.Window
		}
		// DeleteByNameAndBatch holds details about calls to the DeleteByNameAndBatch method.
		DeleteByNameAndBatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// QueueSvc is the queueSvc argument value.
			QueueSvc migration.QueueService
			// Name is the name argument value.
			Name string
			// BatchName is the batchName argument value.
			BatchName string
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetAllByBatch holds details about calls to the GetAllByBatch method.
		GetAllByBatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BatchName is the batchName argument value.
			BatchName string
		}
		// GetByNameAndBatch holds details about calls to the GetByNameAndBatch method.
		GetByNameAndBatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// BatchName is the batchName argument value.
			BatchName string
		}
		// ReplaceByBatch holds details about calls to the ReplaceByBatch method.
		ReplaceByBatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// QueueSvc is the queueSvc argument value.
			QueueSvc migration.QueueService
			// BatchName is the batchName argument value.
			BatchName string
			// Windows is the windows argument value.
			Windows migration.Windows
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Window is the window argument value.
			Window *migration.Window
		}
	}
	lockCreate               sync.RWMutex
	lockDeleteByNameAndBatch sync.RWMutex
	lockGetAll               sync.RWMutex
	lockGetAllByBatch        sync.RWMutex
	lockGetByNameAndBatch    sync.RWMutex
	lockReplaceByBatch       sync.RWMutex
	lockUpdate               sync.RWMutex
}

// Create calls CreateFunc.
func (mock *WindowServiceMock) Create(ctx context.Context, window migration.Window) (migration.Window, error) {
	if mock.CreateFunc == nil {
		panic("WindowServiceMock.CreateFunc: method is nil but WindowService.Create was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Window migration.Window
	}{
		Ctx:    ctx,
		Window: window,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, window)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedWindowService.CreateCalls())
func (mock *WindowServiceMock) CreateCalls() []struct {
	Ctx    context.Context
	Window migration.Window
} {
	var calls []struct {
		Ctx    context.Context
		Window migration.Window
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// DeleteByNameAndBatch calls DeleteByNameAndBatchFunc.
func (mock *WindowServiceMock) DeleteByNameAndBatch(ctx context.Context, queueSvc migration.QueueService, name string, batchName string) error {
	if mock.DeleteByNameAndBatchFunc == nil {
		panic("WindowServiceMock.DeleteByNameAndBatchFunc: method is nil but WindowService.DeleteByNameAndBatch was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		QueueSvc  migration.QueueService
		Name      string
		BatchName string
	}{
		Ctx:       ctx,
		QueueSvc:  queueSvc,
		Name:      name,
		BatchName: batchName,
	}
	mock.lockDeleteByNameAndBatch.Lock()
	mock.calls.DeleteByNameAndBatch = append(mock.calls.DeleteByNameAndBatch, callInfo)
	mock.lockDeleteByNameAndBatch.Unlock()
	return mock.DeleteByNameAndBatchFunc(ctx, queueSvc, name, batchName)
}

// DeleteByNameAndBatchCalls gets all the calls that were made to DeleteByNameAndBatch.
// Check the length with:
//
//	len(mockedWindowService.DeleteByNameAndBatchCalls())
func (mock *WindowServiceMock) DeleteByNameAndBatchCalls() []struct {
	Ctx       context.Context
	QueueSvc  migration.QueueService
	Name      string
	BatchName string
} {
	var calls []struct {
		Ctx       context.Context
		QueueSvc  migration.QueueService
		Name      string
		BatchName string
	}
	mock.lockDeleteByNameAndBatch.RLock()
	calls = mock.calls.DeleteByNameAndBatch
	mock.lockDeleteByNameAndBatch.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *WindowServiceMock) GetAll(ctx context.Context) (migration.Windows, error) {
	if mock.GetAllFunc == nil {
		panic("WindowServiceMock.GetAllFunc: method is nil but WindowService.GetAll was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc(ctx)
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//
//	len(mockedWindowService.GetAllCalls())
func (mock *WindowServiceMock) GetAllCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// GetAllByBatch calls GetAllByBatchFunc.
func (mock *WindowServiceMock) GetAllByBatch(ctx context.Context, batchName string) (migration.Windows, error) {
	if mock.GetAllByBatchFunc == nil {
		panic("WindowServiceMock.GetAllByBatchFunc: method is nil but WindowService.GetAllByBatch was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		BatchName string
	}{
		Ctx:       ctx,
		BatchName: batchName,
	}
	mock.lockGetAllByBatch.Lock()
	mock.calls.GetAllByBatch = append(mock.calls.GetAllByBatch, callInfo)
	mock.lockGetAllByBatch.Unlock()
	return mock.GetAllByBatchFunc(ctx, batchName)
}

// GetAllByBatchCalls gets all the calls that were made to GetAllByBatch.
// Check the length with:
//
//	len(mockedWindowService.GetAllByBatchCalls())
func (mock *WindowServiceMock) GetAllByBatchCalls() []struct {
	Ctx       context.Context
	BatchName string
} {
	var calls []struct {
		Ctx       context.Context
		BatchName string
	}
	mock.lockGetAllByBatch.RLock()
	calls = mock.calls.GetAllByBatch
	mock.lockGetAllByBatch.RUnlock()
	return calls
}

// GetByNameAndBatch calls GetByNameAndBatchFunc.
func (mock *WindowServiceMock) GetByNameAndBatch(ctx context.Context, name string, batchName string) (*migration.Window, error) {
	if mock.GetByNameAndBatchFunc == nil {
		panic("WindowServiceMock.GetByNameAndBatchFunc: method is nil but WindowService.GetByNameAndBatch was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Name      string
		BatchName string
	}{
		Ctx:       ctx,
		Name:      name,
		BatchName: batchName,
	}
	mock.lockGetByNameAndBatch.Lock()
	mock.calls.GetByNameAndBatch = append(mock.calls.GetByNameAndBatch, callInfo)
	mock.lockGetByNameAndBatch.Unlock()
	return mock.GetByNameAndBatchFunc(ctx, name, batchName)
}

// GetByNameAndBatchCalls gets all the calls that were made to GetByNameAndBatch.
// Check the length with:
//
//	len(mockedWindowService.GetByNameAndBatchCalls())
func (mock *WindowServiceMock) GetByNameAndBatchCalls() []struct {
	Ctx       context.Context
	Name      string
	BatchName string
} {
	var calls []struct {
		Ctx       context.Context
		Name      string
		BatchName string
	}
	mock.lockGetByNameAndBatch.RLock()
	calls = mock.calls.GetByNameAndBatch
	mock.lockGetByNameAndBatch.RUnlock()
	return calls
}

// ReplaceByBatch calls ReplaceByBatchFunc.
func (mock *WindowServiceMock) ReplaceByBatch(ctx context.Context, queueSvc migration.QueueService, batchName string, windows migration.Windows) error {
	if mock.ReplaceByBatchFunc == nil {
		panic("WindowServiceMock.ReplaceByBatchFunc: method is nil but WindowService.ReplaceByBatch was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		QueueSvc  migration.QueueService
		BatchName string
		Windows   migration.Windows
	}{
		Ctx:       ctx,
		QueueSvc:  queueSvc,
		BatchName: batchName,
		Windows:   windows,
	}
	mock.lockReplaceByBatch.Lock()
	mock.calls.ReplaceByBatch = append(mock.calls.ReplaceByBatch, callInfo)
	mock.lockReplaceByBatch.Unlock()
	return mock.ReplaceByBatchFunc(ctx, queueSvc, batchName, windows)
}

// ReplaceByBatchCalls gets all the calls that were made to ReplaceByBatch.
// Check the length with:
//
//	len(mockedWindowService.ReplaceByBatchCalls())
func (mock *WindowServiceMock) ReplaceByBatchCalls() []struct {
	Ctx       context.Context
	QueueSvc  migration.QueueService
	BatchName string
	Windows   migration.Windows
} {
	var calls []struct {
		Ctx       context.Context
		QueueSvc  migration.QueueService
		BatchName string
		Windows   migration.Windows
	}
	mock.lockReplaceByBatch.RLock()
	calls = mock.calls.ReplaceByBatch
	mock.lockReplaceByBatch.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *WindowServiceMock) Update(ctx context.Context, window *migration.Window) error {
	if mock.UpdateFunc == nil {
		panic("WindowServiceMock.UpdateFunc: method is nil but WindowService.Update was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Window *migration.Window
	}{
		Ctx:    ctx,
		Window: window,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, window)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedWindowService.UpdateCalls())
func (mock *WindowServiceMock) UpdateCalls() []struct {
	Ctx    context.Context
	Window *migration.Window
} {
	var calls []struct {
		Ctx    context.Context
		Window *migration.Window
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
