// Code generated by generate-event; DO NOT EDIT.

package event

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/google/uuid"

	"github.com/FuturFusion/migration-manager/internal/server/request"
	"github.com/FuturFusion/migration-manager/shared/api"
)

const (
	NetworkImported         api.LifecycleAction = "network-imported"
	NetworkModified         api.LifecycleAction = "network-modified"
	NetworkRemoved          api.LifecycleAction = "network-removed"
	NetworkOverrideModified api.LifecycleAction = "network-override-modified"
)

func NetworkURI(id uuid.UUID) string {
	uri := fmt.Sprintf("/1.0/networks/%s", id)

	return uri
}

func NewNetworkEvent(action api.LifecycleAction, r *http.Request, entity api.Network, id uuid.UUID) api.EventLifecycle {
	b, _ := json.Marshal(entity)

	return api.EventLifecycle{
		Action:    string(action),
		Requestor: request.CreateRequestor(r),
		Entities:  []string{NetworkURI(id)},
		Metadata:  b,
	}
}
