// Code generated by generate-event; DO NOT EDIT.

package event

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/google/uuid"

	"github.com/FuturFusion/migration-manager/internal/server/request"
	"github.com/FuturFusion/migration-manager/shared/api"
)

const (
	QueueEntryCanceled api.LifecycleAction = "queue-entry-canceled"
	QueueEntryRetried  api.LifecycleAction = "queue-entry-retried"
	QueueEntryRemoved  api.LifecycleAction = "queue-entry-removed"
)

func QueueEntryURI(id uuid.UUID) string {
	uri := fmt.Sprintf("/1.0/queue/%s", id)

	return uri
}

func NewQueueEntryEvent(action api.LifecycleAction, r *http.Request, entity api.QueueEntry, id uuid.UUID) api.EventLifecycle {
	b, _ := json.Marshal(entity)

	return api.EventLifecycle{
		Action:    string(action),
		Requestor: request.CreateRequestor(r),
		Entities:  []string{QueueEntryURI(id)},
		Metadata:  b,
	}
}
