// Code generated by generate-event; DO NOT EDIT.

package event

import (
	"encoding/json"
	"net/http"

	"github.com/FuturFusion/migration-manager/internal/server/request"
	"github.com/FuturFusion/migration-manager/shared/api"
)

const (
	SystemNetworkModified api.LifecycleAction = "system-network-modified"
)

func SystemNetworkURI() string {
	return "/1.0/system/network"
}

func NewSystemNetworkEvent(action api.LifecycleAction, r *http.Request, entity api.SystemNetwork) api.EventLifecycle {
	b, _ := json.Marshal(entity)

	return api.EventLifecycle{
		Action:    string(action),
		Requestor: request.CreateRequestor(r),
		Entities:  []string{SystemNetworkURI()},
		Metadata:  b,
	}
}
