// Code generated by generate-event; DO NOT EDIT.

package event

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/FuturFusion/migration-manager/internal/server/request"
	"github.com/FuturFusion/migration-manager/shared/api"
)

const (
	TargetCreated  api.LifecycleAction = "target-created"
	TargetModified api.LifecycleAction = "target-modified"
	TargetRemoved  api.LifecycleAction = "target-removed"
)

func TargetURI(id string) string {
	uri := fmt.Sprintf("/1.0/targets/%s", id)

	return uri
}

func NewTargetEvent(action api.LifecycleAction, r *http.Request, entity api.Target, id string) api.EventLifecycle {
	b, _ := json.Marshal(entity)

	return api.EventLifecycle{
		Action:    string(action),
		Requestor: request.CreateRequestor(r),
		Entities:  []string{TargetURI(id)},
		Metadata:  b,
	}
}
