// Code generated by gowrap. DO NOT EDIT.
// template: ../../../logger/slog.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package middleware

import (
	"context"
	"log/slog"

	_sourceMigration "github.com/FuturFusion/migration-manager/internal/migration"
)

// NetworkRepoWithSlog implements _sourceMigration.NetworkRepo that is instrumented with slog logger
type NetworkRepoWithSlog struct {
	_log  *slog.Logger
	_base _sourceMigration.NetworkRepo
}

// NewNetworkRepoWithSlog instruments an implementation of the _sourceMigration.NetworkRepo with simple logging
func NewNetworkRepoWithSlog(base _sourceMigration.NetworkRepo, log *slog.Logger) NetworkRepoWithSlog {
	return NetworkRepoWithSlog{
		_base: base,
		_log:  log,
	}
}

// Create implements _sourceMigration.NetworkRepo
func (_d NetworkRepoWithSlog) Create(ctx context.Context, network _sourceMigration.Network) (i1 int64, err error) {
	_d._log.With(
		slog.Any("ctx", ctx),
		slog.Any("network", network),
	).Debug("NetworkRepoWithSlog: calling Create")
	defer func() {
		log := _d._log.With(
			slog.Int64("i1", i1),
			slog.Any("err", err),
		)
		if err != nil {
			log.Error("NetworkRepoWithSlog: method Create returned an error")
		} else {
			log.Debug("NetworkRepoWithSlog: method Create finished")
		}
	}()
	return _d._base.Create(ctx, network)
}

// DeleteByName implements _sourceMigration.NetworkRepo
func (_d NetworkRepoWithSlog) DeleteByName(ctx context.Context, name string) (err error) {
	_d._log.With(
		slog.Any("ctx", ctx),
		slog.String("name", name),
	).Debug("NetworkRepoWithSlog: calling DeleteByName")
	defer func() {
		log := _d._log.With(
			slog.Any("err", err),
		)
		if err != nil {
			log.Error("NetworkRepoWithSlog: method DeleteByName returned an error")
		} else {
			log.Debug("NetworkRepoWithSlog: method DeleteByName finished")
		}
	}()
	return _d._base.DeleteByName(ctx, name)
}

// GetAll implements _sourceMigration.NetworkRepo
func (_d NetworkRepoWithSlog) GetAll(ctx context.Context) (n1 _sourceMigration.Networks, err error) {
	_d._log.With(
		slog.Any("ctx", ctx),
	).Debug("NetworkRepoWithSlog: calling GetAll")
	defer func() {
		log := _d._log.With(
			slog.Any("n1", n1),
			slog.Any("err", err),
		)
		if err != nil {
			log.Error("NetworkRepoWithSlog: method GetAll returned an error")
		} else {
			log.Debug("NetworkRepoWithSlog: method GetAll finished")
		}
	}()
	return _d._base.GetAll(ctx)
}

// GetAllNames implements _sourceMigration.NetworkRepo
func (_d NetworkRepoWithSlog) GetAllNames(ctx context.Context) (sa1 []string, err error) {
	_d._log.With(
		slog.Any("ctx", ctx),
	).Debug("NetworkRepoWithSlog: calling GetAllNames")
	defer func() {
		log := _d._log.With(
			slog.Any("sa1", sa1),
			slog.Any("err", err),
		)
		if err != nil {
			log.Error("NetworkRepoWithSlog: method GetAllNames returned an error")
		} else {
			log.Debug("NetworkRepoWithSlog: method GetAllNames finished")
		}
	}()
	return _d._base.GetAllNames(ctx)
}

// GetByName implements _sourceMigration.NetworkRepo
func (_d NetworkRepoWithSlog) GetByName(ctx context.Context, name string) (np1 *_sourceMigration.Network, err error) {
	_d._log.With(
		slog.Any("ctx", ctx),
		slog.String("name", name),
	).Debug("NetworkRepoWithSlog: calling GetByName")
	defer func() {
		log := _d._log.With(
			slog.Any("np1", np1),
			slog.Any("err", err),
		)
		if err != nil {
			log.Error("NetworkRepoWithSlog: method GetByName returned an error")
		} else {
			log.Debug("NetworkRepoWithSlog: method GetByName finished")
		}
	}()
	return _d._base.GetByName(ctx, name)
}

// Rename implements _sourceMigration.NetworkRepo
func (_d NetworkRepoWithSlog) Rename(ctx context.Context, oldName string, newName string) (err error) {
	_d._log.With(
		slog.Any("ctx", ctx),
		slog.String("oldName", oldName),
		slog.String("newName", newName),
	).Debug("NetworkRepoWithSlog: calling Rename")
	defer func() {
		log := _d._log.With(
			slog.Any("err", err),
		)
		if err != nil {
			log.Error("NetworkRepoWithSlog: method Rename returned an error")
		} else {
			log.Debug("NetworkRepoWithSlog: method Rename finished")
		}
	}()
	return _d._base.Rename(ctx, oldName, newName)
}

// Update implements _sourceMigration.NetworkRepo
func (_d NetworkRepoWithSlog) Update(ctx context.Context, network _sourceMigration.Network) (err error) {
	_d._log.With(
		slog.Any("ctx", ctx),
		slog.Any("network", network),
	).Debug("NetworkRepoWithSlog: calling Update")
	defer func() {
		log := _d._log.With(
			slog.Any("err", err),
		)
		if err != nil {
			log.Error("NetworkRepoWithSlog: method Update returned an error")
		} else {
			log.Debug("NetworkRepoWithSlog: method Update finished")
		}
	}()
	return _d._base.Update(ctx, network)
}
