// Code generated by gowrap. DO NOT EDIT.
// template: https://raw.githubusercontent.com/hexdigest/gowrap/bd05dcaf6963696b62ac150a98a59674456c6c53/templates/logrus
// gowrap: http://github.com/hexdigest/gowrap

package middleware

import (
	"context"

	_sourceMigration "github.com/FuturFusion/migration-manager/internal/migration"
	"github.com/sirupsen/logrus"
)

// SourceRepoWithLogrus implements _sourceMigration.SourceRepo that is instrumented with logrus logger
type SourceRepoWithLogrus struct {
	_log  *logrus.Entry
	_base _sourceMigration.SourceRepo
}

// NewSourceRepoWithLogrus instruments an implementation of the _sourceMigration.SourceRepo with simple logging
func NewSourceRepoWithLogrus(base _sourceMigration.SourceRepo, log *logrus.Entry) SourceRepoWithLogrus {
	return SourceRepoWithLogrus{
		_base: base,
		_log:  log,
	}
}

// Create implements _sourceMigration.SourceRepo
func (_d SourceRepoWithLogrus) Create(ctx context.Context, source _sourceMigration.Source) (s1 _sourceMigration.Source, err error) {
	_d._log.WithFields(logrus.Fields(map[string]interface{}{
		"ctx":    ctx,
		"source": source})).Debug("SourceRepoWithLogrus: calling Create")
	defer func() {
		if err != nil {
			_d._log.WithFields(logrus.Fields(map[string]interface{}{
				"s1":  s1,
				"err": err})).Error("SourceRepoWithLogrus: method Create returned an error")
		} else {
			_d._log.WithFields(logrus.Fields(map[string]interface{}{
				"s1":  s1,
				"err": err})).Debug("SourceRepoWithLogrus: method Create finished")
		}
	}()
	return _d._base.Create(ctx, source)
}

// DeleteByName implements _sourceMigration.SourceRepo
func (_d SourceRepoWithLogrus) DeleteByName(ctx context.Context, name string) (err error) {
	_d._log.WithFields(logrus.Fields(map[string]interface{}{
		"ctx":  ctx,
		"name": name})).Debug("SourceRepoWithLogrus: calling DeleteByName")
	defer func() {
		if err != nil {
			_d._log.WithFields(logrus.Fields(map[string]interface{}{
				"err": err})).Error("SourceRepoWithLogrus: method DeleteByName returned an error")
		} else {
			_d._log.WithFields(logrus.Fields(map[string]interface{}{
				"err": err})).Debug("SourceRepoWithLogrus: method DeleteByName finished")
		}
	}()
	return _d._base.DeleteByName(ctx, name)
}

// GetAll implements _sourceMigration.SourceRepo
func (_d SourceRepoWithLogrus) GetAll(ctx context.Context) (s1 _sourceMigration.Sources, err error) {
	_d._log.WithFields(logrus.Fields(map[string]interface{}{
		"ctx": ctx})).Debug("SourceRepoWithLogrus: calling GetAll")
	defer func() {
		if err != nil {
			_d._log.WithFields(logrus.Fields(map[string]interface{}{
				"s1":  s1,
				"err": err})).Error("SourceRepoWithLogrus: method GetAll returned an error")
		} else {
			_d._log.WithFields(logrus.Fields(map[string]interface{}{
				"s1":  s1,
				"err": err})).Debug("SourceRepoWithLogrus: method GetAll finished")
		}
	}()
	return _d._base.GetAll(ctx)
}

// GetByID implements _sourceMigration.SourceRepo
func (_d SourceRepoWithLogrus) GetByID(ctx context.Context, id int) (s1 _sourceMigration.Source, err error) {
	_d._log.WithFields(logrus.Fields(map[string]interface{}{
		"ctx": ctx,
		"id":  id})).Debug("SourceRepoWithLogrus: calling GetByID")
	defer func() {
		if err != nil {
			_d._log.WithFields(logrus.Fields(map[string]interface{}{
				"s1":  s1,
				"err": err})).Error("SourceRepoWithLogrus: method GetByID returned an error")
		} else {
			_d._log.WithFields(logrus.Fields(map[string]interface{}{
				"s1":  s1,
				"err": err})).Debug("SourceRepoWithLogrus: method GetByID finished")
		}
	}()
	return _d._base.GetByID(ctx, id)
}

// GetByName implements _sourceMigration.SourceRepo
func (_d SourceRepoWithLogrus) GetByName(ctx context.Context, name string) (s1 _sourceMigration.Source, err error) {
	_d._log.WithFields(logrus.Fields(map[string]interface{}{
		"ctx":  ctx,
		"name": name})).Debug("SourceRepoWithLogrus: calling GetByName")
	defer func() {
		if err != nil {
			_d._log.WithFields(logrus.Fields(map[string]interface{}{
				"s1":  s1,
				"err": err})).Error("SourceRepoWithLogrus: method GetByName returned an error")
		} else {
			_d._log.WithFields(logrus.Fields(map[string]interface{}{
				"s1":  s1,
				"err": err})).Debug("SourceRepoWithLogrus: method GetByName finished")
		}
	}()
	return _d._base.GetByName(ctx, name)
}

// UpdateByName implements _sourceMigration.SourceRepo
func (_d SourceRepoWithLogrus) UpdateByName(ctx context.Context, source _sourceMigration.Source) (s1 _sourceMigration.Source, err error) {
	_d._log.WithFields(logrus.Fields(map[string]interface{}{
		"ctx":    ctx,
		"source": source})).Debug("SourceRepoWithLogrus: calling UpdateByName")
	defer func() {
		if err != nil {
			_d._log.WithFields(logrus.Fields(map[string]interface{}{
				"s1":  s1,
				"err": err})).Error("SourceRepoWithLogrus: method UpdateByName returned an error")
		} else {
			_d._log.WithFields(logrus.Fields(map[string]interface{}{
				"s1":  s1,
				"err": err})).Debug("SourceRepoWithLogrus: method UpdateByName finished")
		}
	}()
	return _d._base.UpdateByName(ctx, source)
}
