// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/FuturFusion/migration-manager/internal/migration"
	"github.com/FuturFusion/migration-manager/shared/api"
)

// Ensure, that BatchRepoMock does implement migration.BatchRepo.
// If this is not the case, regenerate this file with moq.
var _ migration.BatchRepo = &BatchRepoMock{}

// BatchRepoMock is a mock implementation of migration.BatchRepo.
//
//	func TestSomethingThatUsesBatchRepo(t *testing.T) {
//
//		// make and configure a mocked migration.BatchRepo
//		mockedBatchRepo := &BatchRepoMock{
//			CreateFunc: func(ctx context.Context, batch migration.Batch) (migration.Batch, error) {
//				panic("mock out the Create method")
//			},
//			DeleteByNameFunc: func(ctx context.Context, name string) error {
//				panic("mock out the DeleteByName method")
//			},
//			GetAllFunc: func(ctx context.Context) (migration.Batches, error) {
//				panic("mock out the GetAll method")
//			},
//			GetAllByStateFunc: func(ctx context.Context, status api.BatchStatusType) (migration.Batches, error) {
//				panic("mock out the GetAllByState method")
//			},
//			GetAllNamesFunc: func(ctx context.Context) ([]string, error) {
//				panic("mock out the GetAllNames method")
//			},
//			GetByIDFunc: func(ctx context.Context, id int) (migration.Batch, error) {
//				panic("mock out the GetByID method")
//			},
//			GetByNameFunc: func(ctx context.Context, name string) (migration.Batch, error) {
//				panic("mock out the GetByName method")
//			},
//			UpdateByIDFunc: func(ctx context.Context, batch migration.Batch) (migration.Batch, error) {
//				panic("mock out the UpdateByID method")
//			},
//			UpdateStatusByIDFunc: func(ctx context.Context, id int, status api.BatchStatusType, statusString string) (migration.Batch, error) {
//				panic("mock out the UpdateStatusByID method")
//			},
//		}
//
//		// use mockedBatchRepo in code that requires migration.BatchRepo
//		// and then make assertions.
//
//	}
type BatchRepoMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, batch migration.Batch) (migration.Batch, error)

	// DeleteByNameFunc mocks the DeleteByName method.
	DeleteByNameFunc func(ctx context.Context, name string) error

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func(ctx context.Context) (migration.Batches, error)

	// GetAllByStateFunc mocks the GetAllByState method.
	GetAllByStateFunc func(ctx context.Context, status api.BatchStatusType) (migration.Batches, error)

	// GetAllNamesFunc mocks the GetAllNames method.
	GetAllNamesFunc func(ctx context.Context) ([]string, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id int) (migration.Batch, error)

	// GetByNameFunc mocks the GetByName method.
	GetByNameFunc func(ctx context.Context, name string) (migration.Batch, error)

	// UpdateByIDFunc mocks the UpdateByID method.
	UpdateByIDFunc func(ctx context.Context, batch migration.Batch) (migration.Batch, error)

	// UpdateStatusByIDFunc mocks the UpdateStatusByID method.
	UpdateStatusByIDFunc func(ctx context.Context, id int, status api.BatchStatusType, statusString string) (migration.Batch, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Batch is the batch argument value.
			Batch migration.Batch
		}
		// DeleteByName holds details about calls to the DeleteByName method.
		DeleteByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetAllByState holds details about calls to the GetAllByState method.
		GetAllByState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Status is the status argument value.
			Status api.BatchStatusType
		}
		// GetAllNames holds details about calls to the GetAllNames method.
		GetAllNames []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int
		}
		// GetByName holds details about calls to the GetByName method.
		GetByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// UpdateByID holds details about calls to the UpdateByID method.
		UpdateByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Batch is the batch argument value.
			Batch migration.Batch
		}
		// UpdateStatusByID holds details about calls to the UpdateStatusByID method.
		UpdateStatusByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int
			// Status is the status argument value.
			Status api.BatchStatusType
			// StatusString is the statusString argument value.
			StatusString string
		}
	}
	lockCreate           sync.RWMutex
	lockDeleteByName     sync.RWMutex
	lockGetAll           sync.RWMutex
	lockGetAllByState    sync.RWMutex
	lockGetAllNames      sync.RWMutex
	lockGetByID          sync.RWMutex
	lockGetByName        sync.RWMutex
	lockUpdateByID       sync.RWMutex
	lockUpdateStatusByID sync.RWMutex
}

// Create calls CreateFunc.
func (mock *BatchRepoMock) Create(ctx context.Context, batch migration.Batch) (migration.Batch, error) {
	if mock.CreateFunc == nil {
		panic("BatchRepoMock.CreateFunc: method is nil but BatchRepo.Create was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Batch migration.Batch
	}{
		Ctx:   ctx,
		Batch: batch,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, batch)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedBatchRepo.CreateCalls())
func (mock *BatchRepoMock) CreateCalls() []struct {
	Ctx   context.Context
	Batch migration.Batch
} {
	var calls []struct {
		Ctx   context.Context
		Batch migration.Batch
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// DeleteByName calls DeleteByNameFunc.
func (mock *BatchRepoMock) DeleteByName(ctx context.Context, name string) error {
	if mock.DeleteByNameFunc == nil {
		panic("BatchRepoMock.DeleteByNameFunc: method is nil but BatchRepo.DeleteByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockDeleteByName.Lock()
	mock.calls.DeleteByName = append(mock.calls.DeleteByName, callInfo)
	mock.lockDeleteByName.Unlock()
	return mock.DeleteByNameFunc(ctx, name)
}

// DeleteByNameCalls gets all the calls that were made to DeleteByName.
// Check the length with:
//
//	len(mockedBatchRepo.DeleteByNameCalls())
func (mock *BatchRepoMock) DeleteByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockDeleteByName.RLock()
	calls = mock.calls.DeleteByName
	mock.lockDeleteByName.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *BatchRepoMock) GetAll(ctx context.Context) (migration.Batches, error) {
	if mock.GetAllFunc == nil {
		panic("BatchRepoMock.GetAllFunc: method is nil but BatchRepo.GetAll was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc(ctx)
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//
//	len(mockedBatchRepo.GetAllCalls())
func (mock *BatchRepoMock) GetAllCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// GetAllByState calls GetAllByStateFunc.
func (mock *BatchRepoMock) GetAllByState(ctx context.Context, status api.BatchStatusType) (migration.Batches, error) {
	if mock.GetAllByStateFunc == nil {
		panic("BatchRepoMock.GetAllByStateFunc: method is nil but BatchRepo.GetAllByState was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Status api.BatchStatusType
	}{
		Ctx:    ctx,
		Status: status,
	}
	mock.lockGetAllByState.Lock()
	mock.calls.GetAllByState = append(mock.calls.GetAllByState, callInfo)
	mock.lockGetAllByState.Unlock()
	return mock.GetAllByStateFunc(ctx, status)
}

// GetAllByStateCalls gets all the calls that were made to GetAllByState.
// Check the length with:
//
//	len(mockedBatchRepo.GetAllByStateCalls())
func (mock *BatchRepoMock) GetAllByStateCalls() []struct {
	Ctx    context.Context
	Status api.BatchStatusType
} {
	var calls []struct {
		Ctx    context.Context
		Status api.BatchStatusType
	}
	mock.lockGetAllByState.RLock()
	calls = mock.calls.GetAllByState
	mock.lockGetAllByState.RUnlock()
	return calls
}

// GetAllNames calls GetAllNamesFunc.
func (mock *BatchRepoMock) GetAllNames(ctx context.Context) ([]string, error) {
	if mock.GetAllNamesFunc == nil {
		panic("BatchRepoMock.GetAllNamesFunc: method is nil but BatchRepo.GetAllNames was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAllNames.Lock()
	mock.calls.GetAllNames = append(mock.calls.GetAllNames, callInfo)
	mock.lockGetAllNames.Unlock()
	return mock.GetAllNamesFunc(ctx)
}

// GetAllNamesCalls gets all the calls that were made to GetAllNames.
// Check the length with:
//
//	len(mockedBatchRepo.GetAllNamesCalls())
func (mock *BatchRepoMock) GetAllNamesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAllNames.RLock()
	calls = mock.calls.GetAllNames
	mock.lockGetAllNames.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *BatchRepoMock) GetByID(ctx context.Context, id int) (migration.Batch, error) {
	if mock.GetByIDFunc == nil {
		panic("BatchRepoMock.GetByIDFunc: method is nil but BatchRepo.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedBatchRepo.GetByIDCalls())
func (mock *BatchRepoMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  int
} {
	var calls []struct {
		Ctx context.Context
		ID  int
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// GetByName calls GetByNameFunc.
func (mock *BatchRepoMock) GetByName(ctx context.Context, name string) (migration.Batch, error) {
	if mock.GetByNameFunc == nil {
		panic("BatchRepoMock.GetByNameFunc: method is nil but BatchRepo.GetByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetByName.Lock()
	mock.calls.GetByName = append(mock.calls.GetByName, callInfo)
	mock.lockGetByName.Unlock()
	return mock.GetByNameFunc(ctx, name)
}

// GetByNameCalls gets all the calls that were made to GetByName.
// Check the length with:
//
//	len(mockedBatchRepo.GetByNameCalls())
func (mock *BatchRepoMock) GetByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetByName.RLock()
	calls = mock.calls.GetByName
	mock.lockGetByName.RUnlock()
	return calls
}

// UpdateByID calls UpdateByIDFunc.
func (mock *BatchRepoMock) UpdateByID(ctx context.Context, batch migration.Batch) (migration.Batch, error) {
	if mock.UpdateByIDFunc == nil {
		panic("BatchRepoMock.UpdateByIDFunc: method is nil but BatchRepo.UpdateByID was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Batch migration.Batch
	}{
		Ctx:   ctx,
		Batch: batch,
	}
	mock.lockUpdateByID.Lock()
	mock.calls.UpdateByID = append(mock.calls.UpdateByID, callInfo)
	mock.lockUpdateByID.Unlock()
	return mock.UpdateByIDFunc(ctx, batch)
}

// UpdateByIDCalls gets all the calls that were made to UpdateByID.
// Check the length with:
//
//	len(mockedBatchRepo.UpdateByIDCalls())
func (mock *BatchRepoMock) UpdateByIDCalls() []struct {
	Ctx   context.Context
	Batch migration.Batch
} {
	var calls []struct {
		Ctx   context.Context
		Batch migration.Batch
	}
	mock.lockUpdateByID.RLock()
	calls = mock.calls.UpdateByID
	mock.lockUpdateByID.RUnlock()
	return calls
}

// UpdateStatusByID calls UpdateStatusByIDFunc.
func (mock *BatchRepoMock) UpdateStatusByID(ctx context.Context, id int, status api.BatchStatusType, statusString string) (migration.Batch, error) {
	if mock.UpdateStatusByIDFunc == nil {
		panic("BatchRepoMock.UpdateStatusByIDFunc: method is nil but BatchRepo.UpdateStatusByID was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		ID           int
		Status       api.BatchStatusType
		StatusString string
	}{
		Ctx:          ctx,
		ID:           id,
		Status:       status,
		StatusString: statusString,
	}
	mock.lockUpdateStatusByID.Lock()
	mock.calls.UpdateStatusByID = append(mock.calls.UpdateStatusByID, callInfo)
	mock.lockUpdateStatusByID.Unlock()
	return mock.UpdateStatusByIDFunc(ctx, id, status, statusString)
}

// UpdateStatusByIDCalls gets all the calls that were made to UpdateStatusByID.
// Check the length with:
//
//	len(mockedBatchRepo.UpdateStatusByIDCalls())
func (mock *BatchRepoMock) UpdateStatusByIDCalls() []struct {
	Ctx          context.Context
	ID           int
	Status       api.BatchStatusType
	StatusString string
} {
	var calls []struct {
		Ctx          context.Context
		ID           int
		Status       api.BatchStatusType
		StatusString string
	}
	mock.lockUpdateStatusByID.RLock()
	calls = mock.calls.UpdateStatusByID
	mock.lockUpdateStatusByID.RUnlock()
	return calls
}
