// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/FuturFusion/migration-manager/internal/migration"
)

// Ensure, that TargetRepoMock does implement migration.TargetRepo.
// If this is not the case, regenerate this file with moq.
var _ migration.TargetRepo = &TargetRepoMock{}

// TargetRepoMock is a mock implementation of migration.TargetRepo.
//
//	func TestSomethingThatUsesTargetRepo(t *testing.T) {
//
//		// make and configure a mocked migration.TargetRepo
//		mockedTargetRepo := &TargetRepoMock{
//			CreateFunc: func(ctx context.Context, target migration.Target) (migration.Target, error) {
//				panic("mock out the Create method")
//			},
//			DeleteByNameFunc: func(ctx context.Context, name string) error {
//				panic("mock out the DeleteByName method")
//			},
//			GetAllFunc: func(ctx context.Context) (migration.Targets, error) {
//				panic("mock out the GetAll method")
//			},
//			GetAllNamesFunc: func(ctx context.Context) ([]string, error) {
//				panic("mock out the GetAllNames method")
//			},
//			GetByIDFunc: func(ctx context.Context, id int) (migration.Target, error) {
//				panic("mock out the GetByID method")
//			},
//			GetByNameFunc: func(ctx context.Context, name string) (migration.Target, error) {
//				panic("mock out the GetByName method")
//			},
//			UpdateByNameFunc: func(ctx context.Context, target migration.Target) (migration.Target, error) {
//				panic("mock out the UpdateByName method")
//			},
//		}
//
//		// use mockedTargetRepo in code that requires migration.TargetRepo
//		// and then make assertions.
//
//	}
type TargetRepoMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, target migration.Target) (migration.Target, error)

	// DeleteByNameFunc mocks the DeleteByName method.
	DeleteByNameFunc func(ctx context.Context, name string) error

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func(ctx context.Context) (migration.Targets, error)

	// GetAllNamesFunc mocks the GetAllNames method.
	GetAllNamesFunc func(ctx context.Context) ([]string, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id int) (migration.Target, error)

	// GetByNameFunc mocks the GetByName method.
	GetByNameFunc func(ctx context.Context, name string) (migration.Target, error)

	// UpdateByNameFunc mocks the UpdateByName method.
	UpdateByNameFunc func(ctx context.Context, target migration.Target) (migration.Target, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Target is the target argument value.
			Target migration.Target
		}
		// DeleteByName holds details about calls to the DeleteByName method.
		DeleteByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetAllNames holds details about calls to the GetAllNames method.
		GetAllNames []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int
		}
		// GetByName holds details about calls to the GetByName method.
		GetByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// UpdateByName holds details about calls to the UpdateByName method.
		UpdateByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Target is the target argument value.
			Target migration.Target
		}
	}
	lockCreate       sync.RWMutex
	lockDeleteByName sync.RWMutex
	lockGetAll       sync.RWMutex
	lockGetAllNames  sync.RWMutex
	lockGetByID      sync.RWMutex
	lockGetByName    sync.RWMutex
	lockUpdateByName sync.RWMutex
}

// Create calls CreateFunc.
func (mock *TargetRepoMock) Create(ctx context.Context, target migration.Target) (migration.Target, error) {
	if mock.CreateFunc == nil {
		panic("TargetRepoMock.CreateFunc: method is nil but TargetRepo.Create was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Target migration.Target
	}{
		Ctx:    ctx,
		Target: target,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, target)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedTargetRepo.CreateCalls())
func (mock *TargetRepoMock) CreateCalls() []struct {
	Ctx    context.Context
	Target migration.Target
} {
	var calls []struct {
		Ctx    context.Context
		Target migration.Target
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// DeleteByName calls DeleteByNameFunc.
func (mock *TargetRepoMock) DeleteByName(ctx context.Context, name string) error {
	if mock.DeleteByNameFunc == nil {
		panic("TargetRepoMock.DeleteByNameFunc: method is nil but TargetRepo.DeleteByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockDeleteByName.Lock()
	mock.calls.DeleteByName = append(mock.calls.DeleteByName, callInfo)
	mock.lockDeleteByName.Unlock()
	return mock.DeleteByNameFunc(ctx, name)
}

// DeleteByNameCalls gets all the calls that were made to DeleteByName.
// Check the length with:
//
//	len(mockedTargetRepo.DeleteByNameCalls())
func (mock *TargetRepoMock) DeleteByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockDeleteByName.RLock()
	calls = mock.calls.DeleteByName
	mock.lockDeleteByName.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *TargetRepoMock) GetAll(ctx context.Context) (migration.Targets, error) {
	if mock.GetAllFunc == nil {
		panic("TargetRepoMock.GetAllFunc: method is nil but TargetRepo.GetAll was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc(ctx)
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//
//	len(mockedTargetRepo.GetAllCalls())
func (mock *TargetRepoMock) GetAllCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// GetAllNames calls GetAllNamesFunc.
func (mock *TargetRepoMock) GetAllNames(ctx context.Context) ([]string, error) {
	if mock.GetAllNamesFunc == nil {
		panic("TargetRepoMock.GetAllNamesFunc: method is nil but TargetRepo.GetAllNames was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAllNames.Lock()
	mock.calls.GetAllNames = append(mock.calls.GetAllNames, callInfo)
	mock.lockGetAllNames.Unlock()
	return mock.GetAllNamesFunc(ctx)
}

// GetAllNamesCalls gets all the calls that were made to GetAllNames.
// Check the length with:
//
//	len(mockedTargetRepo.GetAllNamesCalls())
func (mock *TargetRepoMock) GetAllNamesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAllNames.RLock()
	calls = mock.calls.GetAllNames
	mock.lockGetAllNames.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *TargetRepoMock) GetByID(ctx context.Context, id int) (migration.Target, error) {
	if mock.GetByIDFunc == nil {
		panic("TargetRepoMock.GetByIDFunc: method is nil but TargetRepo.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedTargetRepo.GetByIDCalls())
func (mock *TargetRepoMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  int
} {
	var calls []struct {
		Ctx context.Context
		ID  int
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// GetByName calls GetByNameFunc.
func (mock *TargetRepoMock) GetByName(ctx context.Context, name string) (migration.Target, error) {
	if mock.GetByNameFunc == nil {
		panic("TargetRepoMock.GetByNameFunc: method is nil but TargetRepo.GetByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetByName.Lock()
	mock.calls.GetByName = append(mock.calls.GetByName, callInfo)
	mock.lockGetByName.Unlock()
	return mock.GetByNameFunc(ctx, name)
}

// GetByNameCalls gets all the calls that were made to GetByName.
// Check the length with:
//
//	len(mockedTargetRepo.GetByNameCalls())
func (mock *TargetRepoMock) GetByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetByName.RLock()
	calls = mock.calls.GetByName
	mock.lockGetByName.RUnlock()
	return calls
}

// UpdateByName calls UpdateByNameFunc.
func (mock *TargetRepoMock) UpdateByName(ctx context.Context, target migration.Target) (migration.Target, error) {
	if mock.UpdateByNameFunc == nil {
		panic("TargetRepoMock.UpdateByNameFunc: method is nil but TargetRepo.UpdateByName was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Target migration.Target
	}{
		Ctx:    ctx,
		Target: target,
	}
	mock.lockUpdateByName.Lock()
	mock.calls.UpdateByName = append(mock.calls.UpdateByName, callInfo)
	mock.lockUpdateByName.Unlock()
	return mock.UpdateByNameFunc(ctx, target)
}

// UpdateByNameCalls gets all the calls that were made to UpdateByName.
// Check the length with:
//
//	len(mockedTargetRepo.UpdateByNameCalls())
func (mock *TargetRepoMock) UpdateByNameCalls() []struct {
	Ctx    context.Context
	Target migration.Target
} {
	var calls []struct {
		Ctx    context.Context
		Target migration.Target
	}
	mock.lockUpdateByName.RLock()
	calls = mock.calls.UpdateByName
	mock.lockUpdateByName.RUnlock()
	return calls
}
